### PR TITLE
Vcard subitem to viewer

### PR DESCRIPTION
**Pull request by fmpfeifer**
Change VCardParser to generate HTML Preview instead of creating subitems.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Did some tests, seems previous html report formatting is not kept anymore (eg newlines). Could you take a look?

**Comment by fmpfeifer** [comment]
Sure. I'll take a look and report back.

**Comment by fmpfeifer** [comment]
Hi @lfcnassif ,

Fixed. I turns out that the the handler was dropping the style elemtens in resulting html. Thanks.

**Comment by lfcnassif** [comment]
Thank you, @fmpfeifer !

**Pull request merged**
